### ISSUE TITLE
Ordering by UnaryExpression raises TypeError

### ISSUE THREAD

**Issue by TWeatherston** [elmkarami/sqlalchemy-filters-plus#13]
Hey,

Really love the package, great work! :+1: 

I've just been having some difficulty using the order_by with a UnaryExpression. Example from the docs:
```python
MyFilter(data={"order_by": User.first_name.asc()})
```
This results in:

`TypeError: Boolean value of this clause is not defined`

It seems that [this is the offending line](https://github.com/elmkarami/sqlalchemy-filters-plus/blob/0361dd1eb7032dde8b790b56aa9815616eb53116/sqlalchemy_filters/filters.py#L516). Would it be possible to get this changed to something like this?

```python
order_by = self.data.get("order_by", self._order_by)
```

Here's a minimal working example that I was using to test this:

```python
from sqlalchemy import Column, VARCHAR, INTEGER, create_engine
from sqlalchemy.orm import declarative_base, Session
from sqlalchemy_filters import Filter, Field


Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id = Column(INTEGER, primary_key=True)
    name = Column(VARCHAR(64))
    email = Column(VARCHAR(64))


class UserFilter(Filter):
    name = Field()

    class Meta:
        model = User


engine = create_engine("sqlite://")
with Session(engine) as session:
    query = session.query(User)
    my_filter = UserFilter(data={"order_by": User.name.desc()}, query=query)
    query = my_filter.apply()
```

Thanks!

**Comment by elmkarami** [comment]
thank you @TWeatherston for reporting the issue. The fix has been published.
